In [2]:
import numpy as np

**NUMPY INDEXING AND SLICING OF VECTORS**

In [8]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [10]:
arr[0]

1

In [12]:
arr[-1]

30

In [14]:
arr[6]

7

In [16]:
arr[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [18]:
arr[1:3]

array([2, 3])

In [26]:
arr[10:21:2]

array([11, 13, 15, 17, 19, 21])

In [30]:
arr[1:4]

array([2, 3, 4])

**NUMPY INDEXING AND SLICING OF MATRIX**

In [75]:
arr2 = np.arange(1,31).reshape((6,5))
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [77]:
arr2[0]

array([1, 2, 3, 4, 5])

In [79]:
arr2[-1]

array([26, 27, 28, 29, 30])

In [82]:
arr2[0][0]

1

In [84]:
arr2[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [88]:
arr2[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [94]:
arr2[:,1:2] # column at index [1]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]])

In [106]:
type(arr2[:,1:2])

numpy.ndarray

**BOOLEAN INDEXING**

In [117]:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
bool_index = arr3 %2 == 0

In [121]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False])

In [127]:
arr3 = arr3[bool_index]
arr3

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 9