In [2]:
import numpy as np

**Basic Array Creation**

In [10]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [18]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [22]:
a = [1,2,3,4.8,'hello',True]
a

[1, 2, 3, 4.8, 'hello', True]

In [24]:
np.array(a)

array(['1', '2', '3', '4.8', 'hello', 'True'], dtype='<U32')

In [72]:
# VECTOR
l = [1,2,3,4,5,6,7,8,9]
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#MATRIX
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**ARRAY GENERATION FUNCTION**

In [33]:
arr1 = np.arange(1,11,2)
arr1

array([1, 3, 5, 7, 9])

In [45]:
arr2 = np.zeros((5))
print(arr2)
arr3 = np.zeros((5,2))
arr3

[0. 0. 0. 0. 0.]


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
arr2 = np.ones((5))
print(arr2)
arr3 = np.ones((5,2))
arr3

[1. 1. 1. 1. 1.]


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
arr4 = np.linspace(1,5,9)
arr4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

**RANDOM GENERATION FUNCTION**

In [83]:
np.random.rand(10,2)  # RETURNS RANDOM NUMBER BETWEEN 0 AND 1 -> NORMALIZATION

array([[0.09174178, 0.56313569],
       [0.53836245, 0.12653259],
       [0.45367869, 0.63513259],
       [0.03888974, 0.10675938],
       [0.65592429, 0.92780871],
       [0.34367751, 0.86756034],
       [0.09866392, 0.27351647],
       [0.09336861, 0.50617188],
       [0.09671062, 0.81453725],
       [0.61140572, 0.68177275]])

In [106]:
np.random.randn(10)  # RETURNS RANDOM NUMBER BETWEEN -3 AND 3 -> STANDARDIZATION

array([ 2.62258716,  0.37461011,  0.88358692, -0.25952917,  0.72703862,
        1.05433859, -1.21680377,  0.84593   ,  0.24673206,  1.03846975])

In [121]:
np.random.randint(0,10,size = (5,2))

array([[5, 8],
       [0, 4],
       [8, 6],
       [5, 1],
       [0, 2]])

**ARRAY ATTRIBUTES**

In [134]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
arr5.shape

(3, 3)

In [138]:
arr5.size

9

In [140]:
arr.dtype

dtype('int64')

In [151]:
arr.itemsize

8

In [161]:
(arr5.itemsize) * (arr5.size)

72

**ARRAY METHODS**

In [164]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
arr5.min()

1

In [168]:
arr5.max()

9

In [172]:
arr5.mean()

5.0

In [174]:
arr5.std()

2.581988897471611

In [184]:
arr5.argmax()

8

In [186]:
arr5.argmin()

0

In [176]:
arr5.sum()

45

In [178]:
np.sum(arr5,axis = 0)  #axis = 0  means column wise

array([12, 15, 18])

In [182]:
np.sum(arr5,axis = 1)  #axis = 1  means row wise

array([ 6, 15, 24])

**RESHAPING AND RESIZING**

In [229]:
arr6 = np.arange(1,31)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [231]:
arr6.shape

(30,)

In [233]:
arr6.reshape((6,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [235]:
arr6.resize((5,6))

In [237]:
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])